### PR TITLE
Starter files for Spring MVC Lab

### PR DESCRIPTION
**Pull request by jeff-anderson-cscc**
NOTE: You might want to wait until after you finish the String JPA lab before merging this. Also, let me know if you get merge conflicts on pom.xml.

Instructions:
1. If you have not yet done so, merge all changes from the rest controllers and JPA labs to master
1. Merge changes on this pull request to master so it is completely current with all changes to date
1. Back your workspace, open the Intellij IDEA project connected to this repository
1. Open "VCS" -> "Git" -> "Branches" 
1. Choose "master" under "Local Branches" then choose "checkout"
1. Open "VCS -> "Git" -> "Pull"
1. Making sure only "origin/master" is checked under "Branches to merge", click "Pull"
1. Verify that, among other changes, you have two new tests under test/java/edu/cscc/java4/rest/ui
1. Open "VCS" -> "Git" -> "Branches" 
1. Choose "+ New Branch"
1. Enter ``spring-mvc-lab-changes`` as the branch name, confirm "Checkout branch" is checked and press "OK"
1. Get both of the new tests running without changing their source code and without breaking any existing tests
1. Verify the web application runs via your browser by visiting [localhost:8080](http://localhost:8080)
1. Verify the REST application still works properly via Postman
1. Once you are happy with your work, commit all changes
1. Push your new branch to GitHub
1. Open a new pull request and add me as a reviewer

### CODE REVIEW

**Comment by Synergy232** [comment]
Thanks!

**Comment by Synergy232** [comment]
I merged JPA to master and pulled master into Intellij but I don't have the file path test/java/edu/cscc/java4/rest/ui to view the new tests.

**Comment by jeff-anderson-cscc** [comment]
Also merge this branch into master then re-pull it into IntelliJ

**Comment by Synergy232** [comment]
That worked, thanks!

**Pull request merged**
